### ISSUE TITLE
1.20 version crashing on servers

### ISSUE THREAD

**Issue by cavy8** [DavidGmc18/Nature_Arise_PUBLIC#1]
Hello! I'm currently receiving a crash on startup for version 0.3.3, seemingly due to loading client-side code on the server.

[crash-2023-06-12_15.36.44-fml.txt](https://github.com/DavidGmc18/Nature_Arise_PUBLIC/files/11725363/crash-2023-06-12_15.36.44-fml.txt)

**Comment by DavidGmc18** [comment]
This issue is fixed in version 0.3.4. It will be available soon on Curse Forge and Modrinth. Thanks for reporting this issue.
