### ISSUE TITLE
[1.20.1] Crash on create world screen

### ISSUE THREAD

**Issue by MrKashew** [DavidGmc18/Nature_Arise_PUBLIC#2]
[crash-2023-06-18_22.42.30-client.txt](https://github.com/DavidGmc18/Nature_Arise_PUBLIC/files/11784829/crash-2023-06-18_22.42.30-client.txt)

**Comment by DavidGmc18** [comment]
This is fixed in version 0.3.5. Thank you for reporting this issue.
