### ISSUE TITLE
Source Code on GitHub?

### ISSUE THREAD

**Issue by DevDyna** [DavidGmc18/Nature_Arise_PUBLIC#4]
There is only the readme without any description with main branch undefined and only issue track

**Comment by DavidGmc18** [comment]
Source code is not public. If you have a good reason for wanting the source code, I can provide it.

**Comment by DevDyna** [comment]
only a my opinion because if was been public to see the mod anyone could send issues or pull requests much more specific
(else maybe could be right write on read me file something)

[edit. i dont want the source code , only asked the why]

**Comment by ooliver1** [comment]
> Source code is not public. If you have a good reason for wanting the source code, I can provide it.

My question would be why does this repo exist if there is no source? Is it just for the issues page?

**Comment by DavidGmc18** [comment]
For now it is only for issues and maybe in future here will be wiki.
