### ISSUE TITLE
 Berry Bushes Do Not Affect Mob Pathfinding

### ISSUE THREAD

**Issue by nexus671** [DavidGmc18/Nature_Arise_PUBLIC#6]
**Minecraft Version**: 1.20.1
**Forge/Fabric Version**: Fabric

**Description**:
I've noticed an issue with the custom berry bushes introduced in this mod. Unlike the vanilla sweet berry bushes, which mobs avoid due to the damage they deal, the custom bushes do not seem to influence mob pathfinding at all. Mobs will walk through them and take damage without attempting to path around.

**Steps to Reproduce**:
1. Place custom berry bushes from this mod on the ground.
2. Observe mob behavior in proximity to the bushes.

**Expected Behavior**:
Mobs should attempt to path around the berry bushes to avoid taking damage, similar to their behavior with vanilla sweet berry bushes.

**Actual Behavior**:
Mobs walk through the custom berry bushes, taking damage without attempting to avoid them.

Thank you for looking into this!

**Comment by DavidGmc18** [comment]
I am aware of this missing feature. It have been added in 0.6.5, but that is available only for 1.20.1 right now. I am making big changes in NA. After that I will release new version of NA for latest and older versions of MC. If everything goes  right, I will release fix within a week.

**Comment by DavidGmc18** [comment]
Sorry it took longer than I expected. I've just published 0.6.5B on Modrinth and Curse Forge. Thank you for reporting, and if you have any questions, feel free to ask.
