### ISSUE TITLE
Doors doubled when broken

### ISSUE THREAD

**Issue by KreloX** [DavidGmc18/Nature_Arise_PUBLIC#7]
Both fir and maple doors drop two items when broken, one for each block space.

Encountered when playing on 1.20.1 NeoForge

**Comment by DavidGmc18** [comment]
Thank you for reporting this bug. It is fixed in 0.7.1 (Modrinth: https://modrinth.com/mod/nature-arise/version/0.7.1 Curse Forge: https://www.curseforge.com/minecraft/mc-mods/nature-arise/files/5280558).
